#!/bin/bash

uid=`id -u`
gid=`id -g`
builder_img=denver_builder
workdir=`docker inspect -f '{{.Config.WorkingDir}}' $builder_img`
docker exec $builder_img bash -c "cd $PWD; goimports $* ; chown -R $uid:$gid $workdir"
